version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    ports:
    - "5432:5432"
    env_file:
    - ./Back/.env
    volumes:
    - postgresdb:/var/lib/postgresql/data
 
  # pgadmin:
  #   links:
  #   - postgres:postgres
  #   container_name: pgadmin
  #   restart: always
  #   image: dpage/pgadmin4
  #   ports:
  #   - "8080:80"
  #   env_file:
  #   - ./Back/.env
  #   networks:
  #   - postgres
  #   depends_on:
  #     - postgres

  backend:
    container_name: backend
    build: ./Back
    restart: unless-stopped
    ports:
    - "3000:3000"
    env_file:
    - ./Back/.env
    depends_on:
      - postgres

  frontend:
    container_name: frontend
    build: ./Front
    restart: unless-stopped
    ports:
    - "5173:5173"
    depends_on:
      - backend

volumes:
  postgresdb: